### ISSUE TITLE
platform specific ffmpeg

### ISSUE THREAD

**Issue by 0xbrayo** [zackees/static_ffmpeg#2]
I love what this package hopes to achieve, installation of ffmpeg in general is a hustle especially on linux where there are so many versions depending on where on got it. I think you should create another repo for linux-ffmpeg which is would be lighter, but would remove the hustle of checking if ffmpeg is installed on the device before running or whether it's installed on path and other issues.

**Comment by zackees** [comment]
Not going to do a linux-ffmpeg because you can just bundle the binary yourself very easily or use `apt-get install ffmpeg`. If anything I would refactor this static_ffmpeg to use ffmpeg wasm compile so that there is a single binary across all platforms.
