### ISSUE TITLE
feature req: adding ffmpeg path to system path when module is imported

### ISSUE THREAD

**Issue by tikuma-lsuhsc** [zackees/static_ffmpeg#5]
Hey,

I'm developing an FFmpeg-wrapper package called `ffmpegio` (please check it out if you have a chance) and have been looking for a user-friendly way of getting the ffmpeg to their system, and I think what you got here does exactly what I need but need another step.

I'm proposing to make your package to add the ffmpeg directory to system path when `import static_ffmpeg` takes place. This lets users to sys-call `ffmpeg`, making your package useful for users who uses various FFmpeg wrappers not just mine. What do you think?

I've tested the idea on my fork and it does work. If you like the idea, I'd be happy to PR my mods.

Thanks,
Kesh

P.S., (perhaps I should raise another issue but) could you also include ffprobe? They kinda go hand-in-hand.

**Comment by zackees** [comment]
Go ahead and create a pull request and i'll consider merging it

**Comment by zackees** [comment]
Actually I dug into this a little bit. Why would you want ffmpeg from here on the system path? The whole point of static_ffmpeg is that it doesn't modify global state but gives you a stable binary that you can use to run your api. I wouldn't be opposed to having ffprobe in the directory, but this would bloat the package so much that I think it would be time to have one archive per platform like 7z file that can be used to hold ffmpeg and ffprobe, which compress really well because they both link to the same static libraries.

If you want your users to be able to bind to a global version of ffmpeg then let them set it in config file or set an environmental variable like FFMPEGIO_USE_FFMPEG=<path>

**Comment by tikuma-lsuhsc** [comment]
> Why would you want ffmpeg from here on the system path? The whole point of static_ffmpeg is that it doesn't modify global state but gives you a stable binary that you can use to run your api.

I was looking at my fork earlier, and I realize I somehow got a wrong impression on how to use `static_ffmpeg`. So, the basic premise is to use `run.get_platform_executable_or_raise()` to get the exe path, right? (don't even ask what I originally thought it is...) So, `static_ffmpeg` would work fine with my library or other ffmpeg wrappers.

That being said...

> The whole point of static_ffmpeg is that it doesn't modify global state 

right. So, what I'm proposing is to do the following in `__init__.py`

```python
import os

os.environ['path'] += ffmpeg_dir # where the binary is located
```

This does not modify global state and only adds the FFmpeg to the path only during the Python runtime (I think... it could persist for the life the terminal window, but not sure 100%). The only caveat is the permission control flag, which currently you are allowing the user to specify, so my idea may not work if there is any trickery in figuring out the permissions. (I'm a Windows guy so never had to deal with it myself.)

I'll post a PR later for you to look at and let you decide.

As for ffprobe (and packaging binaries in general), yeah, I can 100% understand the concern. I wonder if it's possible for `static_ffmpeg` to download directly from binary hosts so they don't need to be part of the package. I used to do that for the past Windows download site but don't know how they work with the new ones.

**Comment by zackees** [comment]
Hey @tikuma-lsuhsc I've updated the static_ffmpeg to include v5.0 of the ffmpeg and I've also added ffprobe.

Try it out:
https://pypi.org/project/static-ffmpeg/
