### ISSUE TITLE
[Windows] Calling cli `static_ffmpeg` fails if the package path contains space

### ISSUE THREAD

**Issue by tikuma-lsuhsc** [zackees/static_ffmpeg#7]
If the package is installed on a path with a space (e.g, 'C:\Users\User Name\Python\Lib\site-packages\static_ffmpeg`) invoking `static_ffmpeg` command fails with the following error:

```
>static_ffmpeg
'C:\Users\User' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by zackees** [comment]
thanks! I'll work on this now

**Comment by zackees** [comment]
Okay, I believe this has been fixed, can you please run

`python -m pip install static-ffmpeg --upgrade`

And then run:

`static_ffmpeg -version` again and confirm the bug is fixed for you?

**Comment by tikuma-lsuhsc** [comment]
I'll check it out on Wed. (I encountered it on my work PC and I'm off tomorrow)

**Comment by zackees** [comment]
Can you confirm fixed?

**Comment by tikuma-lsuhsc** [comment]
Yes it does! Sorry, it escaped my mind to test the fix. Thanks
